/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tampilan;

import connection.Koneksi;
import static connection.Koneksi.connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class T_CetakT extends javax.swing.JFrame {

    Connection connection;
    /**
     * Creates new form T_CetakT
     */
    public T_CetakT() {
        initComponents();
        tampilkan_dataP();
        tampilkan_tahun();
         b_hapusbulan.setEnabled(false);
        
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        jDialog1.setPreferredSize(new Dimension(200, 600));
        jDialog1.setMinimumSize(new Dimension(400, 350));
        jDialog1.setMaximumSize(new Dimension(400, 350));
        jDialog1.setLocationRelativeTo(this);
        
        setLocationRelativeTo(this);
    }
    
     private void tampilkan_tahun() {
                   
        try {
            connection = Koneksi.connection();
            String sql = "select* from tahun";
            java.sql.Statement stmt = connection.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                c_tahun.addItem(rslt.getString("tahun"));
                
            }
            rslt.last();  
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal memuat tahun");
        }
    
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_p = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_T = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_npT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        c_bulan = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        c_tahun = new javax.swing.JComboBox();
        b_caribulan = new javax.swing.JButton();
        b_hapusbulan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jDialog1.setUndecorated(true);

        t_p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_pMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_p);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jInternalFrame1.setVisible(true);

        tabel_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        jScrollPane1.setViewportView(tabel_T);

        jLabel1.setText("No Pelanggan");

        txt_npT.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        jButton1.setText("cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Bulan :");

        c_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel3.setText("Tahun");

        c_tahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        b_caribulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tampil.png"))); // NOI18N
        b_caribulan.setText("Tampil");
        b_caribulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_caribulanMouseClicked(evt);
            }
        });
        b_caribulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_caribulanActionPerformed(evt);
            }
        });

        b_hapusbulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cetak.png"))); // NOI18N
        b_hapusbulan.setText("Cetak");
        b_hapusbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusbulanActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/oke.png"))); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel4.setText("CETAK TRANSAKSI");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_npT, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_caribulan)
                                .addGap(20, 20, 20)
                                .addComponent(b_hapusbulan)
                                .addGap(0, 101, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(338, 338, 338))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(389, 389, 389))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_npT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(c_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(c_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_caribulan)
                    .addComponent(b_hapusbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_caribulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_caribulanMouseClicked

        b_hapusbulan.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_b_caribulanMouseClicked

    private void b_caribulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_caribulanActionPerformed

        tampilkan_dataT();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_caribulanActionPerformed

    private void b_hapusbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusbulanActionPerformed

        try{
       String NamaFile = "src/report/transaksi.jasper"; 
       Class.forName("com.mysql.jdbc.Driver").newInstance();
       Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/Laundry","root","");
       @SuppressWarnings("rawtypes")
       HashMap hash = new HashMap(2);
       //mengambil parameter dari ireport
       hash.put("bln", c_bulan.getSelectedItem());
       hash.put("thn", c_tahun.getSelectedItem());
       hash.put("np", txt_npT.getText());
       
       File file = new File(NamaFile);
       JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file);
       JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash,koneksi);
       JasperViewer.viewReport(jasperPrint,false);
   }catch(Exception ex){
       System.out.println(ex);
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_b_hapusbulanActionPerformed

    private void t_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_pMouseClicked
        txt_npT.setText(t_p.getValueAt(t_p.getSelectedRow(), 0).toString());
        jDialog1.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jDialog1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_CetakT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_CetakT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_CetakT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_CetakT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_CetakT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_caribulan;
    private javax.swing.JButton b_hapusbulan;
    private javax.swing.JComboBox c_bulan;
    private javax.swing.JComboBox c_tahun;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable t_p;
    private javax.swing.JTable tabel_T;
    private javax.swing.JTextField txt_npT;
    // End of variables declaration//GEN-END:variables

    private void tampilkan_dataP() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("no pelanggan");
        tabelmapel.addColumn("nama");
        tabelmapel.addColumn("no hp");
        tabelmapel.addColumn("alamat");
        
        try {
            connection = Koneksi.connection();
            String sql = "select * from pelanggan";
            java.sql.Statement stmt = connection.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                Object[] o =new Object[4];
                o[0] = rslt.getString("no_pelanggan");
                o[1] = rslt.getString("nama");
                o[2] = rslt.getString("no_hp");
                o[3] = rslt.getString("alamat");
                tabelmapel.addRow(o);
            }
            t_p.setModel(tabelmapel);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data pelanggan");
        }
    
        }
    
     private void tampilkan_dataT() {
        
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("No Nota");
        tabelmapel.addColumn("No Plgn");
        tabelmapel.addColumn("Tgl Masuk");
        tabelmapel.addColumn("Tgl Selesai");
        tabelmapel.addColumn("Status");
        tabelmapel.addColumn("Status Byr");
        tabelmapel.addColumn("Tgl Byr");
        tabelmapel.addColumn("Berat");
        tabelmapel.addColumn("Kategori");
        tabelmapel.addColumn("Jumlah");
        tabelmapel.addColumn("Total Byr");
               
        try {
connection = Koneksi.connection();
            String sql = "select a.no_nota, a.no_pelanggan, a.tgl_masuk, a.tgl_selesai, a.status, a.status_bayar, a.tgl_bayar, b.berat, b.kategori, b.jumlah, b.total_bayar from transaksi a, data_transaksi b where a.no_pelanggan='"+txt_npT.getText()+"' AND MONTH(tgl_masuk) = '"+c_bulan.getSelectedItem()+"' And YEAR(tgl_masuk) = '"+c_tahun.getSelectedItem()+"' AND a.no_nota=b.no_nota";
            java.sql.Statement stmt = connection.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                Object[] o =new Object[11];
                o[0] = rslt.getString("no_nota");
                o[1] = rslt.getString("no_pelanggan");
                o[2] = rslt.getDate("tgl_masuk");
                o[3] = rslt.getDate("tgl_selesai");
                o[4] = rslt.getString("status");
                o[5] = rslt.getString("status_bayar");
                o[6] = rslt.getDate("tgl_bayar");
                o[7] = rslt.getString("berat");
                o[8] = rslt.getString("kategori");
                o[9] = rslt.getString("jumlah");
                o[10] = rslt.getString("total_bayar");
                tabelmapel.addRow(o);
            }
            tabel_T.setModel(tabelmapel);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data transaksi");
        }
    
        }

}
